<?php
	// G O O G L E   W E B   F O N T S
	//--------------------------------------------------------
add_action( 'wp_enqueue_scripts', 'vamico_google_fonts' );
if ( ! function_exists( 'vamico_google_fonts' ) ) {
	function vamico_google_fonts() {
		global $vamico_options;
			$vamico_google_fonts = array(
			array(
				'name'    => 'ABeeZee',
				'variant' => ':400,400italic',
			),
			array( 'name' => 'Abel', 'variant' => ':400' ),
			array( 'name' => 'Abril Fatface', 'variant' => ':400' ),
			array( 'name' => 'Aclonica', 'variant' => ':400' ),
			array( 'name' => 'Acme', 'variant' => ':400' ),
			array( 'name' => 'Actor', 'variant' => ':400' ),
			array( 'name' => 'Adamina', 'variant' => ':400' ),
			array( 'name' => 'Advent Pro', 'variant' => ':400,100,200,300,500,600,700' ),
			array( 'name' => 'Aguafina Script', 'variant' => ':400' ),
			array( 'name' => 'Akronim', 'variant' => ':400' ),
			array( 'name' => 'Aladin', 'variant' => ':400' ),
			array( 'name' => 'Aldrich', 'variant' => ':400' ),
			array( 'name' => 'Alef', 'variant' => ':400,700' ),
			array( 'name' => 'Alegreya', 'variant' => ':400,400italic,700,700italic,900,900italic' ),
			array( 'name' => 'Alegreya SC', 'variant' => ':400,400italic,700,700italic,900,900italic' ),
			array( 'name' => 'Alegreya Sans', 'variant' => ':100,100italic,300,300italic,400,400italic,500,500italic,700,700italic,800,800italic,900,900italic' ),
			array( 'name' => 'Alex Brush', 'variant' => ':400' ),
			array( 'name' => 'Alfa Slab One', 'variant' => ':400' ),
			array( 'name' => 'Alice', 'variant' => ':400' ),
			array( 'name' => 'Alike', 'variant' => ':400' ),
			array( 'name' => 'Alike Angular', 'variant' => ':400' ),
			array( 'name' => 'Allan', 'variant' => ':400,700' ),
			array( 'name' => 'Allerta', 'variant' => ':400' ),
			array( 'name' => 'Allerta Stencil', 'variant' => ':400' ),
			array( 'name' => 'Allura', 'variant' => ':400' ),
			array( 'name' => 'Almendra', 'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Almendra Display', 'variant' => ':400' ),
			array( 'name' => 'Almendra SC,', 'variant' => ':400' ),
			array( 'name' => 'Amarante', 'variant' => ':400' ),
			array( 'name' => 'Amaranth', 'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Amatic SC', 'variant' => ':400' ),
			array( 'name' => 'Amatica SC',	 				'variant' => ':400,700' ),
			array( 'name' => 'Amethysta',	 				'variant' => ':400,700' ),
			array( 'name' => 'Amiko',	 					'variant' => ':400,600,700' ),
			array( 'name' => 'Amiri',	 					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Amita',	 					'variant' => ':400,700' ),
			array( 'name' => 'Anaheim',	 					'variant' => ':400' ),
			array( 'name' => 'Andada',	 					'variant' => ':400' ),
			array( 'name' => 'Andika',	 					'variant' => ':400' ),
			array( 'name' => 'Annie Use Your Telescope',	'variant' => ':400' ),
			array( 'name' => 'Anonymous Pro',	 			'variant' => ':400,700' ),
			array( 'name' => 'Antic',	 					'variant' => ':400' ),
			array( 'name' => 'Antic Didone',	 			'variant' => ':400' ),
			array( 'name' => 'Antic Slab',	 				'variant' => ':400' ),
			array( 'name' => 'Anton',	 					'variant' => ':400' ),
			array( 'name' => 'Arapey',	 					'variant' => ':400,400italic' ),
			array( 'name' => 'Arbutus',	 					'variant' => ':400' ),
			array( 'name' => 'Arbutus Slab',	 			'variant' => ':400' ),
			array( 'name' => 'Architects Daughter',			'variant' => ':400' ),
			array( 'name' => 'Archivo Black',	 			'variant' => ':400' ),
			array( 'name' => 'Archivo Narrow',	 			'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Aref Ruqaa',	 				'variant' => ':400,700' ),
			array( 'name' => 'Arima Madurai',	 			'variant' => ':100,200,300,400,700,800,900' ),
			array( 'name' => 'Arimo',	 					'variant' => ':400,700' ),
			array( 'name' => 'Arizonia',	 				'variant' => ':400' ),
			array( 'name' => 'Armata',	 					'variant' => ':400' ),
			array( 'name' => 'Artifika',	 				'variant' => ':400' ),
			array( 'name' => 'Arvo',	 					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Asap',	 					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Asar',	 					'variant' => ':400' ),
			array( 'name' => 'Asset',	 					'variant' => ':400' ),
			array( 'name' => 'Assistant', 					'variant' => ':400' ),
			array( 'name' => 'Antic',	 					'variant' => ':400' ),
			array( 'name' => 'Arvo',	 					'variant' => ':400,700' ),
			array( 'name' => 'Arsenal',	 					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Asap',	 					'variant' => ':400' ),
			array( 'name' => 'Asar',	 					'variant' => ':400' ),
			array( 'name' => 'Asset',	 					'variant' => ':400' ),
			array( 'name' => 'Assistant',	 				'variant' => ':200,300,400,600,700,800' ),
			array( 'name' => 'Astloch',	 					'variant' => ':400,700' ),
			array( 'name' => 'Asul',	 					'variant' => ':400,700' ),
			array( 'name' => 'Athiti',	 					'variant' => ':200,300,400,500,600,700' ),
			array( 'name' => 'Atma',		 				'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Atomic Age',	 				'variant' => ':400' ),
			array( 'name' => 'Aubrey',	 					'variant' => ':400' ),
			array( 'name' => 'Audiowide ',	 				'variant' => ':400' ),
			array( 'name' => 'Autour One',	 				'variant' => ':400' ),
			array( 'name' => 'Average',	 					'variant' => ':400' ),
			array( 'name' => 'Average Sans',	 			'variant' => ':400' ),
			array( 'name' => 'Averia Gruesa Libre',			'variant' => ':400' ),
			array( 'name' => 'Averia Libre',				'variant' => ':300,300italic,400,400italic,700,700italic' ),
			array( 'name' => 'Averia Sans Libre',			'variant' => ':300,300italic,400,400italic,700,700italic' ),
			array( 'name' => 'Averia Serif Libre',			'variant' => ':300,300italic,400,400italic,700,700italic' ),
			array( 'name' => 'Bad Script',	 				'variant' => ':400' ),
			array( 'name' => 'Baloo',	 					'variant' => ':400' ),
			array( 'name' => 'Baloo Bhai',	 				'variant' => ':400' ),
			array( 'name' => 'Baloo Da',	 				'variant' => ':400' ),
			array( 'name' => 'Baloo Thambi', 				'variant' => ':400' ),
			array( 'name' => 'Balthazar',	 				'variant' => ':400' ),
			array( 'name' => 'Bangers',	 					'variant' => ':400' ),
			array( 'name' => 'Basic',	 					'variant' => ':400' ),
			array( 'name' => 'Baumans',	 					'variant' => ':400' ),
			array( 'name' => 'Belgrano',	 				'variant' => ':400' ),
			array( 'name' => 'Belleza',	 					'variant' => ':400' ),
			array( 'name' => 'BenchNine',	 				'variant' => ':300,400,700' ),
			array( 'name' => 'Bentham',	 					'variant' => ':400' ),
			array( 'name' => 'Berkshire Swash',				'variant' => ':400' ),
			array( 'name' => 'Bevan',	 					'variant' => ':400' ),
			array( 'name' => 'Bigelow Rules',	 			'variant' => ':400' ),
			array( 'name' => 'Bigshot One',					'variant' => ':400' ),
			array( 'name' => 'Bilbo',	 					'variant' => ':400' ),
			array( 'name' => 'Bilbo Swash Caps',			'variant' => ':400' ),
			array( 'name' => 'BioRhyme',	 				'variant' => ':200,300,400,700,800' ),
			array( 'name' => 'Biryani',	 					'variant' => ':200,300,400,600,700,800,900' ),
			array( 'name' => 'Bitter',	 					'variant' => ':400,400italic,700' ),
			array( 'name' => 'Black Ops One',				'variant' => ':400' ),
			array( 'name' => 'Bonbon',	 					'variant' => ':400' ),
			array( 'name' => 'Boogaloo',	 				'variant' => ':400' ),
			array( 'name' => 'Bowlby One',	 				'variant' => ':400' ),
			array( 'name' => 'Bowlby One SC', 				'variant' => ':400' ),
			array( 'name' => 'Brawler',	 					'variant' => ':400' ),
			array( 'name' => 'Bree Serif',	 				'variant' => ':400' ),
			array( 'name' => 'Bubblegum Sans',	 			'variant' => ':400' ),
			array( 'name' => 'Bubbler One',	 				'variant' => ':400' ),
			array( 'name' => 'Buda',	 					'variant' => ':400' ),
			array( 'name' => 'Buenard',	 					'variant' => ':400,700' ),
			array( 'name' => 'Bungee',			 			'variant' => ':400' ),
			array( 'name' => 'Bungee Hairline',	 			'variant' => ':400' ),
			array( 'name' => 'Bungee Inline',	 			'variant' => ':400' ),
			array( 'name' => 'Bungee Outline',	 			'variant' => ':400' ),
			array( 'name' => 'Bungee Shade',	 			'variant' => ':400' ),
			array( 'name' => 'Butcherman',		 			'variant' => ':400' ),
			array( 'name' => 'Butterfly Kids',	 			'variant' => ':400' ),
			array( 'name' => 'Cabin',	 					'variant' => ':400,400italic,500,500italic,600,600italic,700,700italic' ),
			array( 'name' => 'Cabin Condensed',	 			'variant' => ':400,500,600,700' ),
			array( 'name' => 'Cabin Sketch',	 			'variant' => ':400,700' ),
			array( 'name' => 'Caesar Dressing',				'variant' => ':400' ),
			array( 'name' => 'Cagliostro',	 				'variant' => ':400' ),
			array( 'name' => 'Cairo',			 			'variant' => ':200,300,400,600,700,900' ),
			array( 'name' => 'Calligraffitti',	 			'variant' => ':400' ),
			array( 'name' => 'Cambay',	 					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Cambo',	 					'variant' => ':400' ),
			array( 'name' => 'Candal',	 					'variant' => ':400' ),
			array( 'name' => 'Cantarell',	 				'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Cantata One',	 				'variant' => ':400' ),
			array( 'name' => 'Cantora One',	 				'variant' => ':400' ),
			array( 'name' => 'Capriola',	 				'variant' => ':400' ),
			array( 'name' => 'Cardo',	 					'variant' => ':400,400italic,700' ),
			array( 'name' => 'Carme',	 					'variant' => ':400' ),
			array( 'name' => 'Carrois Gothic',	 			'variant' => ':400' ),
			array( 'name' => 'Carrois Gothic SC',			'variant' => ':400' ),
			array( 'name' => 'Carter One',	 				'variant' => ':400' ),
			array( 'name' => 'Catamaran', 					'variant' => ':100,200,300,400,500,600,700,800,900' ),
			array( 'name' => 'Caudex',	 					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Caveat',						'variant' => ':400,700' ),
			array( 'name' => 'Caveat Brush',				'variant' => ':400' ),
			array( 'name' => 'Cedarville Cursive',			'variant' => ':400' ),
			array( 'name' => 'Ceviche One',	 				'variant' => ':400' ),
			array( 'name' => 'Changa',	 					'variant' => ':200,300,400,500,600,700,800' ),
			array( 'name' => 'Changa One',	 				'variant' => ':400,400italic' ),
			array( 'name' => 'Chango',		 				'variant' => ':400' ),
			array( 'name' => 'Chathura',		 			'variant' => ':100,300,400,700,800' ),
			array( 'name' => 'Chau Philomene One',			'variant' => ':400,400italic' ),
			array( 'name' => 'Chela One',	 				'variant' => ':400' ),
			array( 'name' => 'Chelsea Market',	 			'variant' => ':400' ),
			array( 'name' => 'Cherry Cream Soda ',			'variant' => ':400' ),
			array( 'name' => 'Cherry Swash',	 			'variant' => ':400,700' ),
			array( 'name' => 'Chewy',	 					'variant' => ':400' ),
			array( 'name' => 'Chicle',	 					'variant' => ':400' ),
			array( 'name' => 'Chivo',	 					'variant' => ':400,400italic,900,900italic' ),
			array( 'name' => 'Chonburi',					'variant' => ':400' ),
			array( 'name' => 'Cinzel',	 					'variant' => ':400,700,900' ),
			array( 'name' => 'Cinzel Decorative',	 		'variant' => ':400,700,900' ),
			array( 'name' => 'Clicker Script',				'variant' => ':400' ),
			array( 'name' => 'Coda',	 					'variant' => ':400,800' ),
			array( 'name' => 'Coda Caption',	 			'variant' => ':400' ),
			array( 'name' => 'Codystar',	 				'variant' => ':300,400' ),
			array( 'name' => 'Coiny',	 					'variant' => ':400' ),
			array( 'name' => 'Combo',	 					'variant' => ':400' ),
			array( 'name' => 'Comfortaa',	 				'variant' => ':300,400,700' ),
			array( 'name' => 'Coming Soon',	 				'variant' => ':400' ),
			array( 'name' => 'Concert One',	 				'variant' => ':400' ),
			array( 'name' => 'Condiment',	 				'variant' => ':400' ),
			array( 'name' => 'Contrail One',				'variant' => ':400' ),
			array( 'name' => 'Convergence',	 				'variant' => ':400' ),
			array( 'name' => 'Cookie',	 					'variant' => ':400' ),
			array( 'name' => 'Copse',	 					'variant' => ':400' ),
			array( 'name' => 'Corben',	 					'variant' => ':400,700' ),
			array( 'name' => 'Cormorant',	 				'variant' => ':300,300italic,400,400italic,500,500italic,600,600italic,700,700italic' ),
			array( 'name' => 'Cormorant Garamond',			'variant' => ':300,300italic,400,400italic,500,500italic,600,600italic,700,700italic' ),
			array( 'name' => 'Cormorant Infant',			'variant' => ':300,300italic,400,400italic,500,500italic,600,600italic,700,700italic' ),
			array( 'name' => 'Cormorant SC',				'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Cormorant Unicase',	 		'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Cormorant Upright',	 		'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Courgette',	 				'variant' => ':400' ),
			array( 'name' => 'Cousine',	 					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Coustard',	 				'variant' => ':400,900' ),
			array( 'name' => 'Covered By Your Grace',		'variant' => ':400' ),
			array( 'name' => 'Crafty Girls',	 			'variant' => ':400' ),
			array( 'name' => 'Creepster',	 				'variant' => ':400' ),
			array( 'name' => 'Crete Round',	 				'variant' => ':400,400italic' ),
			array( 'name' => 'Crimson Text',	 			'variant' => ':400,400italic,600,600italic,700,700italic' ),
			array( 'name' => 'Croissant One',	 			'variant' => ':400' ),
			array( 'name' => 'Crushed',	 					'variant' => ':400' ),
			array( 'name' => 'Cuprum',	 					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Cutive',	 					'variant' => ':400' ),
			array( 'name' => 'Cutive Mono',					'variant' => ':400' ),
			array( 'name' => 'Damion',	 					'variant' => ':400' ),
			array( 'name' => 'Dancing Script',	 			'variant' => ':400,700' ),
			array( 'name' => 'David Libre',					'variant' => ':400,500,700' ),
			array( 'name' => 'Dawning of a New Day',		'variant' => ':400' ),
			array( 'name' => 'Days One',					'variant' => ':400' ),
			array( 'name' => 'Dekko',						'variant' => ':400' ),
			array( 'name' => 'Delius',						'variant' => ':400' ),
			array( 'name' => 'Delius Swash Caps',			'variant' => ':400' ),
			array( 'name' => 'Delius Unicase',				'variant' => ':400,700' ),
			array( 'name' => 'Della Respira',				'variant' => ':400' ),
			array( 'name' => 'Denk One',					'variant' => ':400' ),
			array( 'name' => 'Devonshire',					'variant' => ':400' ),
			array( 'name' => 'Dhurjati',					'variant' => ':400' ),
			array( 'name' => 'Didact Gothic',				'variant' => ':400' ),
			array( 'name' => 'Diplomata',					'variant' => ':400' ),
			array( 'name' => 'Diplomata SC',				'variant' => ':400' ),
			array( 'name' => 'Domine',						'variant' => ':400,700' ),
			array( 'name' => 'Donegal One',					'variant' => ':400' ),
			array( 'name' => 'Doppio One',					'variant' => ':400' ),
			array( 'name' => 'Dorsa ',						'variant' => ':400' ),
			array( 'name' => 'Dosis',						'variant' => ':200,300,400,500,600,700,800' ),
			array( 'name' => 'Dr Sugiyama',					'variant' => ':400' ),
			array( 'name' => 'Droid Sans',					'variant' => ':400,700' ),
			array( 'name' => 'Droid Sans Mono',				'variant' => ':400' ),
			array( 'name' => 'Droid Serif',					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Duru Sans',					'variant' => ':400' ),
			array( 'name' => 'Dynalight',					'variant' => ':400' ),
			array( 'name' => 'EB Garamond',					'variant' => ':400' ),
			array( 'name' => 'Eagle Lake',					'variant' => ':400' ),
			array( 'name' => 'Eater',						'variant' => ':400' ),
			array( 'name' => 'Economica',					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Eczar',						'variant' => ':400,500,600,700,800' ),
			array( 'name' => 'Ek Mukta',					'variant' => ':200,300,400,500,600,700,800' ),
			array( 'name' => 'El Messiri',					'variant' => ':400,500,600,700' ),
			array( 'name' => 'Electrolize',					'variant' => ':400' ),
			array( 'name' => 'Elsie',						'variant' => ':400,900' ),
			array( 'name' => 'Elsie Swash Caps',			'variant' => ':400,900' ),
			array( 'name' => 'Emblema One',					'variant' => ':400' ),
			array( 'name' => 'Emilys Candy',				'variant' => ':400' ),
			array( 'name' => 'Engagement ',					'variant' => ':400' ),
			array( 'name' => 'Englebert',					'variant' => ':400' ),
			array( 'name' => 'Enriqueta',					'variant' => ':400,700' ),
			array( 'name' => 'Erica One',					'variant' => ':400' ),
			array( 'name' => 'Esteban',						'variant' => ':400' ),
			array( 'name' => 'Euphoria Script',				'variant' => ':400' ),
			array( 'name' => 'Ewert',						'variant' => ':400' ),
			array( 'name' => 'Exo',							'variant' => ':100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic' ),
			array( 'name' => 'Exo 2',						'variant' => ':100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic' ),
			array( 'name' => 'Expletus Sans',				'variant' => ':400,400italic,500,500italic,600,600italic,700,700italic' ),
			array( 'name' => 'Fanwood Text',				'variant' => ':400,400italic' ),
			array( 'name' => 'Farsan',						'variant' => ':400' ),
			array( 'name' => 'Fascinate',					'variant' => ':400' ),
			array( 'name' => 'Fascinate Inline',			'variant' => ':400' ),
			array( 'name' => 'Faster One',					'variant' => ':400' ),
			array( 'name' => 'Fauna One',					'variant' => ':400' ),
			array( 'name' => 'Federant',					'variant' => ':400' ),
			array( 'name' => 'Federo',						'variant' => ':400' ),
			array( 'name' => 'Felipa',						'variant' => ':400' ),
			array( 'name' => 'Fenix',						'variant' => ':400' ),
			array( 'name' => 'Finger Paint',				'variant' => ':400' ),
			array( 'name' => 'Fira Mono',					'variant' => ':400,700' ),
			array( 'name' => 'Fira Sans',					'variant' => ':300,300italic,400,400italic,500,500italic,700,700italic' ),
			array( 'name' => 'Fjalla One',					'variant' => ':400' ),
			array( 'name' => 'Felipa',						'variant' => ':400' ),
			array( 'name' => 'Fjord One',					'variant' => ':400' ),
			array( 'name' => 'Flamenco',					'variant' => ':300,400' ),
			array( 'name' => 'Flavors',						'variant' => ':400' ),
			array( 'name' => 'Fondamento',					'variant' => ':400,400italic' ),
			array( 'name' => 'Fontdiner Swanky',			'variant' => ':400' ),
			array( 'name' => 'Forum',						'variant' => ':400' ),
			array( 'name' => 'Francois One',				'variant' => ':400' ),
			array( 'name' => 'Frank Ruhl Libre',			'variant' => ':300,400,500,700,900' ),
			array( 'name' => 'Freckle Face',				'variant' => ':400' ),
			array( 'name' => 'Fredericka the Great',		'variant' => ':400' ),
			array( 'name' => 'Fredoka One',					'variant' => ':400' ),
			array( 'name' => 'Fresca',						'variant' => ':400' ),
			array( 'name' => 'Frijole',						'variant' => ':400' ),
			array( 'name' => 'Fruktur',						'variant' => ':400' ),
			array( 'name' => 'Fugaz One',					'variant' => ':400' ),
			array( 'name' => 'Gabriela',					'variant' => ':400' ),
			array( 'name' => 'Gafata',						'variant' => ':400' ),
			array( 'name' => 'Galada',						'variant' => ':400' ),
			array( 'name' => 'Galdeano',					'variant' => ':400' ),
			array( 'name' => 'Galindo',						'variant' => ':400' ),
			array( 'name' => 'Gentium Basic',				'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Gentium Book Basic',			'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Geo',							'variant' => ':400,400italic' ),
			array( 'name' => 'Geostar',						'variant' => ':400' ),
			array( 'name' => 'Geostar Fill',				'variant' => ':400' ),
			array( 'name' => 'Germania One',				'variant' => ':400' ),
			array( 'name' => 'Gilda Display',				'variant' => ':400' ),
			array( 'name' => 'Give You Glory',				'variant' => ':400' ),
			array( 'name' => 'Glass Antiqua',				'variant' => ':400' ),
			array( 'name' => 'Glegoo',						'variant' => ':400,700' ),
			array( 'name' => 'Gloria Hallelujah',			'variant' => ':400' ),
			array( 'name' => 'Gloria Ha',					'variant' => ':400' ),
			array( 'name' => 'Gochi Hand',					'variant' => ':400' ),
			array( 'name' => 'Gorditas',					'variant' => ':400,700' ),
			array( 'name' => 'Goudy Bookletter 1911',		'variant' => ':400' ),
			array( 'name' => 'Graduate',					'variant' => ':400' ),
			array( 'name' => 'Grand Hotel',					'variant' => ':400' ),
			array( 'name' => 'Gravitas One',				'variant' => ':400' ),
			array( 'name' => 'Great Vibes',					'variant' => ':400' ),
			array( 'name' => 'Griffy',						'variant' => ':400' ),
			array( 'name' => 'Gruppo',						'variant' => ':400' ),
			array( 'name' => 'Gudea',						'variant' => ':400,400italic,700' ),
			array( 'name' => 'Habibi',						'variant' => ':400' ),
			array( 'name' => 'Halant',						'variant' => ':300,400,500,600,700italic' ),
			array( 'name' => 'Hammersmith One',				'variant' => ':400' ),
			array( 'name' => 'Hanalei',						'variant' => ':400' ),
			array( 'name' => 'Hanalei Fill',				'variant' => ':400' ),
			array( 'name' => 'Handlee',						'variant' => ':400' ),
			array( 'name' => 'Happy Monkey',				'variant' => ':400' ),
			array( 'name' => 'Harmattan',					'variant' => ':400' ),
			array( 'name' => 'Headland One',				'variant' => ':400' ),
			array( 'name' => 'Heebo',						'variant' => ':100,300,400,500,700,800,900' ),
			array( 'name' => 'Henny Penny',					'variant' => ':400' ),
			array( 'name' => 'Herr Von Muellerhoff',		'variant' => ':400' ),
			array( 'name' => 'Hind',						'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Hind Guntur',					'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Hind Madurai',				'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Hind Siliguri',				'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Hind Vadodara',				'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Holtwood One SC',				'variant' => ':400' ),
			array( 'name' => 'Homemade Apple',				'variant' => ':400' ),
			array( 'name' => 'Homenaje',					'variant' => ':400' ),
			array( 'name' => 'IM Fell DW Pica',				'variant' => ':400,400italic' ),
			array( 'name' => 'IM Fell Double Pica',			'variant' => ':400,400italic' ),
			array( 'name' => 'IM Fell Double Pica SC',		'variant' => ':400' ),
			array( 'name' => 'IM Fell English',				'variant' => ':400,400italic' ),
			array( 'name' => 'IM Fell English SC',			'variant' => ':400' ),
			array( 'name' => 'IM Fell French Canon',		'variant' => ':400,400italic' ),
			array( 'name' => 'IM Fell French Canon SC',		'variant' => ':400' ),
			array( 'name' => 'IM Fell Great Primer',		'variant' => ':400,400italic' ),
			array( 'name' => 'IM Fell Great Primer SC',		'variant' => ':400' ),
			array( 'name' => 'Iceberg',						'variant' => ':400' ),
			array( 'name' => 'Iceland',						'variant' => ':400' ),
			array( 'name' => 'Imprima',						'variant' => ':400' ),
			array( 'name' => 'Inconsolata',					'variant' => ':400,700' ),
			array( 'name' => 'Inder',						'variant' => ':400' ),
			array( 'name' => 'Indie Flower',				'variant' => ':400' ),
			array( 'name' => 'Inika',						'variant' => ':400,700' ),
			array( 'name' => 'Inknut Antiqua',				'variant' => ':300,400,500,600,700,800,900' ),
			array( 'name' => 'Irish Grover',				'variant' => ':400,700' ),
			array( 'name' => 'Istok Web',					'variant' => ':400,700' ),
			array( 'name' => 'Italiana',					'variant' => ':400' ),
			array( 'name' => 'Italianno',					'variant' => ':400' ),
			array( 'name' => 'Itim',						'variant' => ':400' ),
			array( 'name' => 'Jacques Francois',			'variant' => ':400' ),
			array( 'name' => 'Jacques Francois Shadow',		'variant' => ':400' ),
			array( 'name' => 'Jaldi',						'variant' => ':400,700' ),
			array( 'name' => 'Jim Nightshade',				'variant' => ':400' ),
			array( 'name' => 'Jockey One',					'variant' => ':400' ),
			array( 'name' => 'Jolly Lodger',				'variant' => ':400' ),
			array( 'name' => 'Jomhuria',					'variant' => ':400' ),
			array( 'name' => 'Josefin Sans',				'variant' => ':100,100italic,300,300italic,400,400italic,600,600italic,700,700italic' ),
			array( 'name' => 'Josefin Slab',				'variant' => ':100,100italic,300,300italic,400,400italic,600,600italic,700,700italic' ),
			array( 'name' => 'Joti One',					'variant' => ':400' ),
			array( 'name' => 'Judson',						'variant' => ':400,400italic,700' ),
			array( 'name' => 'Julee',						'variant' => ':400' ),
			array( 'name' => 'Julius Sans One',				'variant' => ':400' ),
			array( 'name' => 'Junge',						'variant' => ':400' ),
			array( 'name' => 'Jura',						'variant' => ':300,400,500,600' ),
			array( 'name' => 'Just Another Hand',			'variant' => ':400' ),
			array( 'name' => 'Just Me Again Down Here',		'variant' => ':400' ),
			array( 'name' => 'Kadwa',						'variant' => ':400,700' ),
			array( 'name' => 'Kalam',						'variant' => ':300,400,700' ),
			array( 'name' => 'Kameron',						'variant' => ':400,700' ),
			array( 'name' => 'Kanit',						'variant' => ':100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic' ),
			array( 'name' => 'Karla',						'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Karma',						'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Katibeh',						'variant' => ':400' ),
			array( 'name' => 'Kaushan Script',				'variant' => ':400' ),
			array( 'name' => 'Kavivanar',					'variant' => ':400' ),
			array( 'name' => 'Kavoon',						'variant' => ':400' ),
			array( 'name' => 'Keania One',					'variant' => ':400' ),
			array( 'name' => 'Kelly Slab',					'variant' => ':400' ),
			array( 'name' => 'Kenia',						'variant' => ':400' ),
			array( 'name' => 'Khand',						'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Khula',						'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Kite One',					'variant' => ':400' ),
			array( 'name' => 'Knewave',						'variant' => ':400' ),
			array( 'name' => 'Kotta One',					'variant' => ':400' ),
			array( 'name' => 'Kranky',						'variant' => ':400' ),
			array( 'name' => 'Kreon',						'variant' => ':300,400,700' ),
			array( 'name' => 'Kristi',						'variant' => ':400' ),
			array( 'name' => 'Krona One',					'variant' => ':400' ),
			array( 'name' => 'Kumar One,',					'variant' => ':400' ),
			array( 'name' => 'Kumar One Outline',			'variant' => ':400' ),
			array( 'name' => 'Kurale',						'variant' => ':400' ),
			array( 'name' => 'La Belle Aurore',				'variant' => ':400' ),
			array( 'name' => 'Laila',						'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Lakki Reddy',					'variant' => ':400' ),
			array( 'name' => 'Lalezar',						'variant' => ':400' ),
			array( 'name' => 'Lancelot',					'variant' => ':400' ),
			array( 'name' => 'Lateef',						'variant' => ':400' ),
			array( 'name' => 'Lato',						'variant' => ':100,100italic,300,300italic,400,400italic,700,700italic,900,900italic' ),
			array( 'name' => 'League Script',				'variant' => ':400' ),
			array( 'name' => 'Leckerli One',				'variant' => ':400' ),
			array( 'name' => 'Ledger',						'variant' => ':400' ),
			array( 'name' => 'Lekton',						'variant' => ':400,400italic,700' ),
			array( 'name' => 'Lemon',						'variant' => ':400' ),
			array( 'name' => 'Lemonada',					'variant' => ':400' ),
			array( 'name' => 'Libre Baskerville',			'variant' => ':400,400italic,700' ),
			array( 'name' => 'Libre Franklin',				'variant' => ':100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic' ),
			array( 'name' => 'Life Savers',					'variant' => ':400,700' ),
			array( 'name' => 'Lilita One',					'variant' => ':400' ),
			array( 'name' => 'Lily Script One',				'variant' => ':400' ),
			array( 'name' => 'Limelight',					'variant' => ':400' ),
			array( 'name' => 'Linden Hill',					'variant' => ':400,400italic' ),
			array( 'name' => 'Lobster',						'variant' => ':400' ),
			array( 'name' => 'Lobster Two',					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Londrina Outline',			'variant' => ':400' ),
			array( 'name' => 'Londrina Shadow',				'variant' => ':400' ),
			array( 'name' => 'Londrina Sketch',				'variant' => ':400' ),
			array( 'name' => 'Londrina Solid',				'variant' => ':400' ),
			array( 'name' => 'Lora',						'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Love Ya Like A Sister',		'variant' => ':400' ),
			array( 'name' => 'Loved by the King',			'variant' => ':400' ),
			array( 'name' => 'Lovers Quarrel',				'variant' => ':400' ),
			array( 'name' => 'Luckiest Guy',				'variant' => ':400' ),
			array( 'name' => 'Lusitana',					'variant' => ':400,700' ),
			array( 'name' => 'Lustria',						'variant' => ':400' ),
			array( 'name' => 'Macondo',						'variant' => ':400' ),
			array( 'name' => 'Macondo Swash Caps',			'variant' => ':400' ),
			array( 'name' => 'Mada',						'variant' => ':300,400,500,900' ),
			array( 'name' => 'Magra',						'variant' => ':400,700' ),
			array( 'name' => 'Maiden Orange',				'variant' => ':400' ),
			array( 'name' => 'Maitree',						'variant' => ':200,300,400,500,600,700' ),
			array( 'name' => 'Mako',						'variant' => ':400' ),
			array( 'name' => 'Mallanna',					'variant' => ':400' ),
			array( 'name' => 'Mandali',						'variant' => ':400' ),
			array( 'name' => 'Marcellus',					'variant' => ':400' ),
			array( 'name' => 'Marcellus SC',				'variant' => ':400' ),
			array( 'name' => 'Marck Script',				'variant' => ':400' ),
			array( 'name' => 'Margarine',					'variant' => ':400' ),
			array( 'name' => 'Marko One',					'variant' => ':400' ),
			array( 'name' => 'Marmelad',					'variant' => ':400' ),
			array( 'name' => 'Martel',						'variant' => ':200,300,400,600,700,800,900' ),
			array( 'name' => 'Martel Sans',					'variant' => ':200,300,400,600,700,800,900' ),
			array( 'name' => 'Marvel',						'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Mate',						'variant' => ':400,400italic' ),
			array( 'name' => 'Mate SC',						'variant' => ':400' ),
			array( 'name' => 'Maven Pro',					'variant' => ':400,500,700,900' ),
			array( 'name' => 'McLaren',						'variant' => ':400' ),
			array( 'name' => 'Meddon',						'variant' => ':400' ),
			array( 'name' => 'MedievalSharp',				'variant' => ':400' ),
			array( 'name' => 'Medula One',					'variant' => ':400' ),
			array( 'name' => 'Meera Inimai',				'variant' => ':400' ),
			array( 'name' => 'Megrim',						'variant' => ':400' ),
			array( 'name' => 'Meie Script',					'variant' => ':400' ),
			array( 'name' => 'Merienda',					'variant' => ':400,700' ),
			array( 'name' => 'Merienda One',				'variant' => ':400' ),
			array( 'name' => 'Merriweather',				'variant' => ':300,300italic,400,400italic,700,700italic' ),
			array( 'name' => 'Merriweather Sans',			'variant' => ':300,300italic,400,400italic,700,700italic' ),
			array( 'name' => 'Metal Mania',					'variant' => ':400' ),
			array( 'name' => 'Metamorphous',				'variant' => ':400' ),
			array( 'name' => 'Metrophobic ',				'variant' => ':400' ),
			array( 'name' => 'Michroma',					'variant' => ':400' ),
			array( 'name' => 'Milonga',						'variant' => ':400' ),
			array( 'name' => 'Miltonian',					'variant' => ':400' ),
			array( 'name' => 'Miltonian Tattoo',			'variant' => ':400' ),
			array( 'name' => 'Miniver',						'variant' => ':400' ),
			array( 'name' => 'Miriam Libre',				'variant' => ':400,700' ),
			array( 'name' => 'Modern Antiqua',				'variant' => ':400' ),
			array( 'name' => 'Mirza',						'variant' => ':400,500,600,700' ),
			array( 'name' => 'Miss Fajardose',				'variant' => ':400' ),
			array( 'name' => 'Mitr',						'variant' => ':200,300,400,500,600,700' ),
			array( 'name' => 'Modak',						'variant' => ':400' ),
			array( 'name' => 'Modern Antiqua',				'variant' => ':400' ),
			array( 'name' => 'Mogra',						'variant' => ':400' ),
			array( 'name' => 'Molengo',						'variant' => ':400' ),
			array( 'name' => 'Molle',						'variant' => ':400italic' ),
			array( 'name' => 'Monda',						'variant' => ':400,700' ),
			array( 'name' => 'Monofett',					'variant' => ':400' ),
			array( 'name' => 'Monoton',						'variant' => ':400' ),
			array( 'name' => 'Monsieur La Doulaise',		'variant' => ':400' ),
			array( 'name' => 'Montaga',						'variant' => ':400' ),
			array( 'name' => 'Montez',						'variant' => ':400' ),
			array( 'name' => 'Montserrat',					'variant' => ':400,700' ),
			array( 'name' => 'Montserrat Alternates',		'variant' => ':400,700' ),
			array( 'name' => 'Montserrat Subrayada',		'variant' => ':400,700' ),
			array( 'name' => 'Mountains of Christmas',		'variant' => ':400,700' ),
			array( 'name' => 'Mouse Memoirs',				'variant' => ':400' ),
			array( 'name' => 'Mr Bedfort',					'variant' => ':400' ),
			array( 'name' => 'Mr Dafoe',					'variant' => ':400' ),
			array( 'name' => 'Mr De Haviland',				'variant' => ':400' ),
			array( 'name' => 'Mrs Saint Delafield',			'variant' => ':400' ),
			array( 'name' => 'Mukta Vaani',					'variant' => ':200,300,400,500,600,700,800' ),
			array( 'name' => 'Muli',						'variant' => ':300,300italic,400,400italic' ),
			array( 'name' => 'Mystery Quest',				'variant' => ':400' ),
			array( 'name' => 'NTR',							'variant' => ':400' ),
			array( 'name' => 'Neucha',						'variant' => ':400' ),
			array( 'name' => 'Neuton',						'variant' => ':200,300,400,400italic,700,800' ),
			array( 'name' => 'New Rocker',					'variant' => ':400' ),
			array( 'name' => 'News Cycle',					'variant' => ':400,700' ),
			array( 'name' => 'Niconne',						'variant' => ':400' ),
			array( 'name' => 'Nixie One',					'variant' => ':400' ),
			array( 'name' => 'Nobile',						'variant' => ':400' ),
			array( 'name' => 'Norican',						'variant' => ':400' ),
			array( 'name' => 'Nosifer',						'variant' => ':400' ),
			array( 'name' => 'Nothing You Could Do',		'variant' => ':400' ),
			array( 'name' => 'Noticia Text',				'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Noto Sans',					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Noto Serif',					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Nova Cut',					'variant' => ':400' ),
			array( 'name' => 'Nova Flat',					'variant' => ':400' ),
			array( 'name' => 'Nova Mono',					'variant' => ':400' ),
			array( 'name' => 'Nova Oval',					'variant' => ':400' ),
			array( 'name' => 'Nova Round',					'variant' => ':400' ),
			array( 'name' => 'Nova Script',					'variant' => ':400' ),
			array( 'name' => 'Nova Slim',					'variant' => ':400' ),
			array( 'name' => 'Nova Square',					'variant' => ':400' ),
			array( 'name' => 'Numans',						'variant' => ':400' ),
			array( 'name' => 'Nunito',						'variant' => ':300,400,700' ),
			array( 'name' => 'Offside',						'variant' => ':400' ),
			array( 'name' => 'Old Standard TT',				'variant' => ':400,400italic,700' ),
			array( 'name' => 'Oldenburg',					'variant' => ':400' ),
			array( 'name' => 'Oleo Script',					'variant' => ':400,700' ),
			array( 'name' => 'Oleo Script Swash Caps',		'variant' => ':400,700' ),
			array( 'name' => 'Open Sans',					'variant' => ':300,300italic,400,400italic,600,600italic,700,700italic' ),
			array( 'name' => 'Open Sans Condensed',			'variant' => ':300,300italic,700' ),
			array( 'name' => 'Oranienbaum',					'variant' => ':400' ),
			array( 'name' => 'Orbitron',					'variant' => ':400,500,700,900' ),
			array( 'name' => 'Oregano',						'variant' => ':400,400italic' ),
			array( 'name' => 'Orienta',						'variant' => ':400' ),
			array( 'name' => 'Original Surfer',				'variant' => ':400' ),
			array( 'name' => 'Oswald',						'variant' => ':300,400,700' ),
			array( 'name' => 'Over the Rainbow',			'variant' => ':400' ),
			array( 'name' => 'Overlock',					'variant' => ':400,400italic,700,700italic,900,900italic' ),
			array( 'name' => 'Overlock SC',					'variant' => ':400' ),
			array( 'name' => 'Ovo',							'variant' => ':400' ),
			array( 'name' => 'Oxygen',						'variant' => ':300,400,700' ),
			array( 'name' => 'Oxygen Mono',					'variant' => ':400' ),
			array( 'name' => 'PT Mono',						'variant' => ':400' ),
			array( 'name' => 'PT Sans',						'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'PT Serif Caption',			'variant' => ':400,700' ),
			array( 'name' => 'PT Sans Narrow',				'variant' => ':400,700' ),
			array( 'name' => 'PT Serif',					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'PT Serif Caption',			'variant' => ':400,700' ),
			array( 'name' => 'Pacifico',					'variant' => ':400' ),
			array( 'name' => 'Palanquin',					'variant' => ':100,200,300,400,500,600,700' ),
			array( 'name' => 'Palanquin Dark',				'variant' => ':400,500,600,700' ),
			array( 'name' => 'Paprika',						'variant' => ':400' ),
			array( 'name' => 'Parisienne',					'variant' => ':400' ),
			array( 'name' => 'Passero One',					'variant' => ':400' ),
			array( 'name' => 'Passion One',					'variant' => ':400' ),
			array( 'name' => 'Pathway Gothic One',			'variant' => ':400' ),
			array( 'name' => 'Patrick Hand',				'variant' => ':400' ),
			array( 'name' => 'Patrick Hand SC',				'variant' => ':400' ),
			array( 'name' => 'Pattaya',						'variant' => ':400' ),
			array( 'name' => 'Patua One',					'variant' => ':400' ),
			array( 'name' => 'Pavanam',						'variant' => ':400' ),
			array( 'name' => 'Paytone One',					'variant' => ':400' ),
			array( 'name' => 'Peddana',						'variant' => ':400' ),
			array( 'name' => 'Peralta',						'variant' => ':400' ),
			array( 'name' => 'Permanent Marker',			'variant' => ':400' ),
			array( 'name' => 'Petit Formal Script',			'variant' => ':400' ),
			array( 'name' => 'Petrona',						'variant' => ':400' ),
			array( 'name' => 'Philosopher',					'variant' => ':400,700' ),
			array( 'name' => 'Piedrat',						'variant' => ':400' ),
			array( 'name' => 'Pinyon Script',				'variant' => ':400' ),
			array( 'name' => 'Pirata One',					'variant' => ':400' ),
			array( 'name' => 'Plaster',						'variant' => ':400' ),
			array( 'name' => 'Play',						'variant' => ':400,700' ),
			array( 'name' => 'Playball',					'variant' => ':400' ),
			array( 'name' => 'Playfair Display',			'variant' => ':400,400italic,700,700italic,900,900italic' ),
			array( 'name' => 'Playfair Display SC',			'variant' => ':400,400italic,700,700italic,900,900italic' ),
			array( 'name' => 'Podkova',						'variant' => ':400,700' ),
			array( 'name' => 'Poiret One',					'variant' => ':400' ),
			array( 'name' => 'Poller One',					'variant' => ':400' ),
			array( 'name' => 'Poly',						'variant' => ':400,400italic' ),
			array( 'name' => 'Pompiere',					'variant' => ':400' ),
			array( 'name' => 'Pontano Sans',				'variant' => ':400' ),
			array( 'name' => 'Poppins',						'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Port Lligat Sans',			'variant' => ':400' ),
			array( 'name' => 'Port Lligat Slab',			'variant' => ':400' ),
			array( 'name' => 'Pragati Narrow',				'variant' => ':400,700' ),
			array( 'name' => 'Prata',						'variant' => ':400' ),
			array( 'name' => 'Press Start 2P',				'variant' => ':400' ),
			array( 'name' => 'Pridi',						'variant' => ':200,300,400,500,600,700' ),
			array( 'name' => 'Princess Sofia',				'variant' => ':400' ),
			array( 'name' => 'Prociono',					'variant' => ':400' ),
			array( 'name' => 'Prompt',						'variant' => ':100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic' ),
			array( 'name' => 'Prosto One',					'variant' => ':400' ),
			array( 'name' => 'Proza Libre',					'variant' => ':400,400italic,500,500italic,600,600italic,700,700italic,800,800italic' ),
			array( 'name' => 'Puritan',						'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Purple Purse',				'variant' => ':400' ),
			array( 'name' => 'Quando',						'variant' => ':400' ),
			array( 'name' => 'Quantico',					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Quattrocento',				'variant' => ':400,700' ),
			array( 'name' => 'Quattrocento Sans',			'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Questrial',					'variant' => ':400' ),
			array( 'name' => 'Quicksand',					'variant' => ':300,400,700' ),
			array( 'name' => 'Quintessential',				'variant' => ':400' ),
			array( 'name' => 'Qwigley',						'variant' => ':400' ),
			array( 'name' => 'Racing Sans One',				'variant' => ':400' ),
			array( 'name' => 'Radley',						'variant' => ':400,400italic' ),
			array( 'name' => 'Rajdhani',					'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Rakkas',						'variant' => ':400' ),
			array( 'name' => 'Raleway',						'variant' => ':100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic' ),
			array( 'name' => 'Raleway Dots',				'variant' => ':400' ),
			array( 'name' => 'Ramabhadra',					'variant' => ':400' ),
			array( 'name' => 'Ramaraja',					'variant' => ':400' ),
			array( 'name' => 'Rambla',						'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Rammetto One',				'variant' => ':400' ),
			array( 'name' => 'Ranchers',					'variant' => ':400' ),
			array( 'name' => 'Rancho',						'variant' => ':400' ),
			array( 'name' => 'Ranga',						'variant' => ':400,700' ),
			array( 'name' => 'Rasa',						'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Rationale',					'variant' => ':400' ),
			array( 'name' => 'Ravi Prakash',				'variant' => ':400' ),
			array( 'name' => 'Redressed',					'variant' => ':400' ),
			array( 'name' => 'Reem Kufi',					'variant' => ':400' ),
			array( 'name' => 'Reenie Beanie',				'variant' => ':400' ),
			array( 'name' => 'Revalia',						'variant' => ':400' ),
			array( 'name' => 'Rhodium Libre',				'variant' => ':400' ),
			array( 'name' => 'Ribeye',						'variant' => ':400' ),
			array( 'name' => 'Ribeye Marrow',				'variant' => ':400' ),
			array( 'name' => 'Righteous',					'variant' => ':400' ),
			array( 'name' => 'Risque',						'variant' => ':400' ),
			array( 'name' => 'Roboto',						'variant' => ':100,100italic,300,300italic,400,400italic,500,500italic,700,700italic,900,900italic' ),
			array( 'name' => 'Roboto Condensed',			'variant' => ':300,300italic,400,400italic,700,700italic' ),
			array( 'name' => 'Roboto Mono',					'variant' => ':100,100italic,300,300italic,400,400italic,500,500italic,700,700italic' ),
			array( 'name' => 'Roboto Slab',					'variant' => ':300,300italic,400,400italic,700,700italic' ),
			array( 'name' => 'Rochester',					'variant' => ':400' ),
			array( 'name' => 'Rock Salt',					'variant' => ':400' ),
			array( 'name' => 'Rokkitt',						'variant' => ':400,700' ),
			array( 'name' => 'Romanesco',					'variant' => ':400' ),
			array( 'name' => 'Ropa Sans',					'variant' => ':400,400italic' ),
			array( 'name' => 'Rosario',						'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Rosarivo',					'variant' => ':400,400italic' ),
			array( 'name' => 'Rouge Script',				'variant' => ':400' ),
			array( 'name' => 'Rozha One',					'variant' => ':400' ),
			array( 'name' => 'Rubik',						'variant' => ':300,300italic,400,400italic,500,500italic,700,700italic,900,900italic' ),
			array( 'name' => 'Rubik Mono One',				'variant' => ':400' ),
			array( 'name' => 'Rubik One',					'variant' => ':400' ),
			array( 'name' => 'Ruda',						'variant' => ':400,700,900' ),
			array( 'name' => 'Rufina',						'variant' => ':400,700' ),
			array( 'name' => 'Ruge Boogie',					'variant' => ':400' ),
			array( 'name' => 'Ruluko',						'variant' => ':400' ),
			array( 'name' => 'Rum Raisin',					'variant' => ':400' ),
			array( 'name' => 'Russo One',					'variant' => ':400' ),
			array( 'name' => 'Ruthie',						'variant' => ':400' ),
			array( 'name' => 'Rye',							'variant' => ':400' ),
			array( 'name' => 'Sacramento',					'variant' => ':400' ),
			array( 'name' => 'Sahitya',						'variant' => ':400,700' ),
			array( 'name' => 'Sail',						'variant' => ':400' ),
			array( 'name' => 'Salsa',						'variant' => ':400' ),
			array( 'name' => 'Sanchez',						'variant' => ':400,400italic' ),
			array( 'name' => 'Sancreek',					'variant' => ':400' ),
			array( 'name' => 'Sansita One',					'variant' => ':400' ),
			array( 'name' => 'Sarala',						'variant' => ':400,700' ),
			array( 'name' => 'Sarina',						'variant' => ':400' ),
			array( 'name' => 'Sarpanch',					'variant' => ':400,500,600,700,800,900' ),
			array( 'name' => 'Satisfy',						'variant' => ':400' ),
			array( 'name' => 'Scada',						'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Scheherazade',				'variant' => ':400,700' ),
			array( 'name' => 'Schoolbell',					'variant' => ':400' ),
			array( 'name' => 'Scope One',					'variant' => ':400' ),
			array( 'name' => 'Seaweed Script',				'variant' => ':400' ),
			array( 'name' => 'Secular One',					'variant' => ':400' ),
			array( 'name' => 'Sevillana',					'variant' => ':400' ),
			array( 'name' => 'Seymour One',					'variant' => ':400' ),
			array( 'name' => 'Shadows Into Light',			'variant' => ':400' ),
			array( 'name' => 'Shadows Into Light Two',		'variant' => ':400' ),
			array( 'name' => 'Shanti',						'variant' => ':400' ),
			array( 'name' => 'Share',						'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Share Tech Mono',				'variant' => ':400' ),
			array( 'name' => 'Shojumaru',					'variant' => ':400' ),
			array( 'name' => 'Short Stack',					'variant' => ':400' ),
			array( 'name' => 'Shrikhand',					'variant' => ':400' ),
			array( 'name' => 'Sigmar One',					'variant' => ':400' ),
			array( 'name' => 'Signika',						'variant' => ':300,400,600,700' ),
			array( 'name' => 'Signika Negative',			'variant' => ':300,400,600,700' ),
			array( 'name' => 'Simonetta',					'variant' => ':400,400italic,900,900italic' ),
			array( 'name' => 'Sintony',						'variant' => ':400,700' ),
			array( 'name' => 'Sirin Stencil',				'variant' => ':400' ),
			array( 'name' => 'Six Caps',					'variant' => ':400' ),
			array( 'name' => 'Skranji',						'variant' => ':400,700' ),
			array( 'name' => 'Slabo 13px ',					'variant' => ':400' ),
			array( 'name' => 'Slabo 27px',					'variant' => ':400' ),
			array( 'name' => 'Slackey',						'variant' => ':400' ),
			array( 'name' => 'Smokum',						'variant' => ':400' ),
			array( 'name' => 'Smythe',						'variant' => ':400' ),
			array( 'name' => 'Sniglet',						'variant' => ':400,800' ),
			array( 'name' => 'Snippet',						'variant' => ':400' ),
			array( 'name' => 'Snowburst One',				'variant' => ':400' ),
			array( 'name' => 'Sofadi One',					'variant' => ':400' ),
			array( 'name' => 'Sofia',						'variant' => ':400' ),
			array( 'name' => 'Sonsie One',					'variant' => ':400' ),
			array( 'name' => 'Sorts Mill Goudy',			'variant' => ':400,400italic' ),
			array( 'name' => 'Source Code Pro',				'variant' => ':200,300,400,500,600,700,900' ),
			array( 'name' => 'Source Sans Pro',				'variant' => ':200,200italic,300,300italic,400,400italic,600,600italic,700,700italic,900,900italic' ),
			array( 'name' => 'Source Serif Pro',			'variant' => ':400,600,700' ),
			array( 'name' => 'Space Mono',					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Special Elite',				'variant' => ':400' ),
			array( 'name' => 'Spicy Rice',					'variant' => ':400' ),
			array( 'name' => 'Spinnaker',					'variant' => ':400' ),
			array( 'name' => 'Spirax',						'variant' => ':400' ),
			array( 'name' => 'Squada One',					'variant' => ':400' ),
			array( 'name' => 'Sree Krushnadevaraya',		'variant' => ':400' ),
			array( 'name' => 'Sriracha',					'variant' => ':400' ),
			array( 'name' => 'Stalemate',					'variant' => ':400' ),
			array( 'name' => 'Stalinist One',				'variant' => ':400' ),
			array( 'name' => 'Stardos Stencil',				'variant' => ':400' ),
			array( 'name' => 'Stint Ultra Condensed',		'variant' => ':400' ),
			array( 'name' => 'Stint Ultra Expanded',		'variant' => ':400' ),
			array( 'name' => 'Stoke',						'variant' => ':300,400' ),
			array( 'name' => 'Strait',						'variant' => ':400' ),
			array( 'name' => 'Sue Ellen Francisco',			'variant' => ':400' ),
			array( 'name' => 'Suez One',					'variant' => ':400' ),
			array( 'name' => 'Sumana',						'variant' => ':400,700' ),
			array( 'name' => 'Sunshiney',					'variant' => ':400' ),
			array( 'name' => 'Supermercado One',			'variant' => ':400' ),
			array( 'name' => 'Sura',						'variant' => ':400,700' ),
			array( 'name' => 'Suranna',						'variant' => ':400' ),
			array( 'name' => 'Suravaram',					'variant' => ':400' ),
			array( 'name' => 'Swanky and Moo Moo',			'variant' => ':400' ),
			array( 'name' => 'Syncopate',					'variant' => ':400,700' ),
			array( 'name' => 'Tangerine',					'variant' => ':400,700' ),
			array( 'name' => 'Tauri',						'variant' => ':400' ),
			array( 'name' => 'Taviraj',						'variant' => ':100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic' ),
			array( 'name' => 'Teko',						'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Telex',						'variant' => ':400' ),
			array( 'name' => 'Tenali Ramakrishna',			'variant' => ':400' ),
			array( 'name' => 'Tenor Sans',					'variant' => ':400' ),
			array( 'name' => 'Text Me One',					'variant' => ':400' ),
			array( 'name' => 'The Girl Next Door',			'variant' => ':400' ),
			array( 'name' => 'Tienne',						'variant' => ':400,700,900' ),
			array( 'name' => 'Tillana',						'variant' => ':400,500,600,700,800' ),
			array( 'name' => 'Timmana',						'variant' => ':400' ),
			array( 'name' => 'Tinos',						'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Titan One',					'variant' => ':400' ),
			array( 'name' => 'Titillium Web',				'variant' => ':200,200italic,300,300italic,400,400italic,600,600italic,700,700italic,900,900italic' ),
			array( 'name' => 'Trade Winds',					'variant' => ':400' ),
			array( 'name' => 'Trirong',						'variant' => ':100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic' ),
			array( 'name' => 'Trocchi',						'variant' => ':400' ),
			array( 'name' => 'Trochut',						'variant' => ':400,400italic,700' ),
			array( 'name' => 'Trykker',						'variant' => ':400' ),
			array( 'name' => 'Tulpen One',					'variant' => ':400' ),
			array( 'name' => 'Ubuntu',						'variant' => ':300,300italic,400,400italic,500,500italic,700,700italic' ),
			array( 'name' => 'Ubuntu Condensed',			'variant' => ':400' ),
			array( 'name' => 'Ubuntu Mono',					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Ultra',						'variant' => ':400' ),
			array( 'name' => 'Uncial Antiqua',				'variant' => ':400' ),
			array( 'name' => 'Underdog',					'variant' => ':400' ),
			array( 'name' => 'Unica One',					'variant' => ':400' ),
			array( 'name' => 'UnifrakturCook',				'variant' => ':400' ),
			array( 'name' => 'UnifrakturMaguntia',			'variant' => ':400' ),
			array( 'name' => 'Unkempt',						'variant' => ':400' ),
			array( 'name' => 'Unlock',						'variant' => ':400' ),
			array( 'name' => 'Unna',						'variant' => ':400' ),
			array( 'name' => 'VT323',						'variant' => ':400' ),
			array( 'name' => 'Vampiro One',					'variant' => ':400' ),
			array( 'name' => 'Varela',						'variant' => ':400' ),
			array( 'name' => 'Varela Round',				'variant' => ':400' ),
			array( 'name' => 'Vast Shadow',					'variant' => ':400' ),
			array( 'name' => 'Vesper Libre',				'variant' => ':400,500,700,900' ),
			array( 'name' => 'Vibur',						'variant' => ':400' ),
			array( 'name' => 'Vidaloka',					'variant' => ':400' ),
			array( 'name' => 'Viga',						'variant' => ':400' ),
			array( 'name' => 'Voces',						'variant' => ':400' ),
			array( 'name' => 'Volkhov',						'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Vollkorn',					'variant' => ':400,400italic,700,700italic' ),
			array( 'name' => 'Voltaire',					'variant' => ':400' ),
			array( 'name' => 'Waiting for the Sunrise',		'variant' => ':400' ),
			array( 'name' => 'Wallpoet',					'variant' => ':400' ),
			array( 'name' => 'Walter Turncoat',				'variant' => ':400' ),
			array( 'name' => 'Warnes',						'variant' => ':400' ),
			array( 'name' => 'Wellfleet',					'variant' => ':400' ),
			array( 'name' => 'Wendy One',					'variant' => ':400' ),
			array( 'name' => 'Wire One',					'variant' => ':400' ),
			array( 'name' => 'Work Sans',					'variant' => ':100,200,300,400,500,600,700,800,900' ),
			array( 'name' => 'Yanone Kaffeesatz',			'variant' => ':200,300,400,700' ),
			array( 'name' => 'Yantramanav',					'variant' => ':100,200,300,400,500,700,900' ),
			array( 'name' => 'Yatra One',					'variant' => ':400' ),
			array( 'name' => 'Yellowtail',					'variant' => ':400' ),
			array( 'name' => 'Yeseva One',					'variant' => ':400' ),
			array( 'name' => 'Yesteryear',					'variant' => ':400' ),
			array( 'name' => 'Yrsa',						'variant' => ':300,400,500,600,700' ),
			array( 'name' => 'Zeyada',						'variant' => ':400' ),
		);
		$fonts = array();
		// Go through the font options
		if ( ! empty( $vamico_options ) ) {
			foreach ( $vamico_options as $key => $option ) {

				$option_types = $option['type'];

				if ( $option_types == 'custom_google_fonts' ) {

					foreach ( $vamico_google_fonts as $font ) {
						$vamico_googlefont = get_option( $option['id'] );
						if ( $vamico_googlefont === $font['name'] && ! in_array( $font['name'], $fonts ) ) {
							$fonts[] = str_replace( ' ', '+', $font['name'] ) . $font['variant'];
						}
					}
				}
			}
		}

		// Output google font css in header
		$vamico_google_font_url = '';
		// Output google font css in header
		if ( ! is_admin() ) {
			if ( $fonts ) {
				$query_args = array( 'family' => implode( '%7c', $fonts ) );
				$vamico_google_font_url = add_query_arg( $query_args, '//fonts.googleapis.com/css' );
			}
		}
		if ( $vamico_google_font_url  ) {
			wp_enqueue_style( 'vamico_google_fonts', $vamico_google_font_url, null, null );
		}
		return $vamico_google_fonts;
}
}
